# Generated by Django 5.2.7 on 2025-11-12 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empNo', models.IntegerField()),
                ('empName', models.CharField(max_length=200)),
                ('phoneNo', models.IntegerField()),
                ('emailAddress', models.CharField(max_length=100)),
                ('salary', models.IntegerField()),
            ],
        ),
    ]
