# Generated by Django 5.2.7 on 2025-12-01 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empName', models.CharField(max_length=200)),
                ('empNo', models.IntegerField()),
                ('designation', models.CharField()),
            ],
        ),
    ]
