# Generated by Django 5.2.7 on 2025-11-21 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeDetailModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empId', models.IntegerField()),
                ('empName', models.CharField(max_length=200)),
                ('phoneNum', models.IntegerField()),
                ('email', models.CharField(max_length=200)),
            ],
        ),
    ]
